scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        max_x: 0.7
        max_y: 0.7
        max_z: 0.4
        min_x: -0.7
        min_y: -0.7
        min_z: -0.4
        
        invert: false # activate to remove all points outside of the box
