controller_manager:
  ros__parameters:
    update_rate: 100

    manip_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

manip_joint_trajectory_controller:
  ros__parameters:
    joints:
      - link1_to_link2
      - link2_to_ee
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity